name: Build and test application

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: "25"
      gradle-task:
        required: false
        type: string
        description: Gradle task to run (build and test)
        default: "./gradlew build installDist --configuration-cache"
      upload-artifact:
        required: false
        type: boolean
        default: false
        description: Upload build artifact for Docker image builds
      generate-dependency-graph:
        required: false
        type: boolean
        default: false
        description: Generate and submit dependency graph

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}

      - name: Generate and submit dependency graph
        if: ${{ inputs.generate-dependency-graph == true }}
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # ratchet:gradle/actions/setup-gradle@v5
        env: # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit

      - name: Build and test application
        env:
          GRADLE_TASK: ${{ inputs.gradle-task }}
        run: $GRADLE_TASK

      - name: Upload build artifact
        if: ${{ inputs.upload-artifact == true }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6
        with:
          name: gradle-build-${{ github.run_id }}
          path: build/
          retention-days: 1
