name: Build & test PR

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: Node version to build with
        default: '22'
      pnpm-version:
        required: false
        type: string
        description: pnpm version to build with
        default: '10'
      server-directory:
        required: false
        type: string
        description: Server directory path
        default: 'server'
      server-build-command:
        required: false
        type: string
        description: Command to build the server
        default: 'pnpm run build'
      app-build-command:
        required: false
        type: string
        description: Command to build the app
        default: 'pnpm run build'

jobs:
  build-test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # ratchet:pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # ratchet:actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies for client
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Install dependencies for server
        if: ${{ ! cancelled() && hashFiles('server/package.json') != '' }}
        working-directory: ${{ inputs.server-directory }}
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build server
        if: ${{ ! cancelled() && hashFiles('server/package.json') != '' }}
        working-directory: ${{ inputs.server-directory }}
        run: $SERVER_BUILD_COMMAND
        env:
          SERVER_BUILD_COMMAND: ${{ inputs.server-build-command }}

      - name: Build app
        run: $APP_BUILD_COMMAND
        env:
          APP_BUILD_COMMAND: ${{ inputs.app-build-command }}
