name: Squawk Migration Lint

on:
  workflow_call:

jobs:
  squawk-migration-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Find modified migrations
        run: |
          modified_migrations=$(git diff --diff-filter=d --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF 'src/main/resources/db/migration/*.sql' | tr '\n' ' ')
          echo "Migration files: $modified_migrations"
          echo "file_names=$modified_migrations" >> $GITHUB_OUTPUT
        id: modified-migrations

      - name: Run Squawk Lint
        uses: sbdchd/squawk-action@68d739e098ab69cf46c64fdbf6175bb29d195a16 # ratchet:sbdchd/squawk-action@v2
        with:
          files: ${{ steps.modified-migrations.outputs.file_names }}
